// Clean, self-contained B-spline core: evaluation and knot insertion for a
// scalar function or a plain / rational / complex-rational curve, open or
// periodic, over a scalar-field abstraction.
export * from './types'
export * from './complex'
export * from './basis'
export * from './coeffs'
export * from './evaluate'
export * from './indexing'
export * from './insert'
export * from './elevate'
export * from './bernstein'
export * from './complexBernstein'
export * from './curvature'
export * from './gradient'
export * from './linalg'
export * from './optimize'
export * from './symmetryReduction'
export * from './curvatureProblem'
export * from './function'
